name: CI -Project_Go

on:
   push:
    branches:
      - main
   pull_request:
    branches:
      - main
      
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go 
              uses: actions/setup-go@v3
              with:
                go-version : 1.20

            - name: Install Make 
              run: |
                   sudo apt update
                   sudo apt install -y make

            - name: Test
              run: make test

            - name: Build
              run: make build   

            - name: Connect to EC2 instance
              uses: appleboy/ssh-action@master
              with:
                 host: ${{secrets.EC2_PUBLIC_IP}}
                 username: ubuntu
                 key: ${{secrets.EC2_SSH_KEY}}
                 script: |
                  echo "Connected to AWS EC2 instance"
                  cd eCommerce-smart_gads
                  git pull
                  make build
                  cd ~
                  sudo systemctl restart myapp.service

          